import type { ExerciseDef } from '../package-fitness/types';

export const presetExercises: ExerciseDef[] = [
  // ==================== 胸部 (15) ====================
  { id: 'incline-bb-bench', name: '上斜杠铃卧推', muscleGroup: '胸', subMuscleGroup: '上胸', equipment: '杠铃', type: '推', imageUrl: '', tags: ['推力', '上肢'] },
  { id: 'incline-db-bench', name: '上斜哑铃卧推', muscleGroup: '胸', subMuscleGroup: '上胸', equipment: '哑铃', type: '推', imageUrl: '', tags: ['推力', '上肢'] },
  { id: 'incline-smith-bench', name: '上斜史密斯卧推', muscleGroup: '胸', subMuscleGroup: '上胸', equipment: '固定器械', type: '推' },
  { id: 'flat-bb-bench', name: '平板杠铃卧推', muscleGroup: '胸', subMuscleGroup: '中胸', equipment: '杠铃', type: '推', imageUrl: '', tags: ['推力', '上肢'] },
  { id: 'flat-db-bench', name: '平板哑铃卧推', muscleGroup: '胸', subMuscleGroup: '中胸', equipment: '哑铃', type: '推', imageUrl: '', tags: ['推力', '上肢'] },
  { id: 'hs-bench', name: '悍马机卧推', muscleGroup: '胸', subMuscleGroup: '中胸', equipment: '悍马机', type: '推' },
  { id: 'machine-bench', name: '器械卧推', muscleGroup: '胸', subMuscleGroup: '中胸', equipment: '固定器械', type: '推' },
  { id: 'decline-bb-bench', name: '下斜杠铃卧推', muscleGroup: '胸', subMuscleGroup: '下胸', equipment: '杠铃', type: '推' },
  { id: 'decline-db-bench', name: '下斜哑铃卧推', muscleGroup: '胸', subMuscleGroup: '下胸', equipment: '哑铃', type: '推' },
  { id: 'dip-chest', name: '双杠臂屈伸', muscleGroup: '胸', subMuscleGroup: '下胸', equipment: '徒手', type: '推' },
  { id: 'db-fly', name: '哑铃飞鸟', muscleGroup: '胸', subMuscleGroup: '中胸', equipment: '哑铃', type: '推' },
  { id: 'cable-fly', name: '绳索夹胸', muscleGroup: '胸', subMuscleGroup: '中胸', equipment: '绳索', type: '推' },
  { id: 'cable-cross', name: '龙门架飞鸟', muscleGroup: '胸', subMuscleGroup: '下胸', equipment: '绳索', type: '推' },
  { id: 'pushup', name: '俯卧撑', muscleGroup: '胸', subMuscleGroup: '中胸', equipment: '徒手', type: '推' },
  { id: 'wide-pushup', name: '宽距俯卧撑', muscleGroup: '胸', subMuscleGroup: '上胸', equipment: '徒手', type: '推' },
  // ==================== 背部 (12) ====================
  { id: 'pullup', name: '引体向上', muscleGroup: '背', subMuscleGroup: '宽度', equipment: '徒手', type: '拉', imageUrl: '', tags: ['拉力', '上肢'] },
  { id: 'lat-pulldown', name: '高位下拉', muscleGroup: '背', subMuscleGroup: '宽度', equipment: '绳索', type: '拉', imageUrl: '', tags: ['拉力', '上肢'] },
  { id: 'wide-seated-row', name: '宽距坐姿划船', muscleGroup: '背', subMuscleGroup: '宽度', equipment: '绳索', type: '拉' },
  { id: 'bb-row', name: '杠铃划船', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '杠铃', type: '拉', imageUrl: '', tags: ['拉力', '上肢'] },
  { id: 'db-row', name: '哑铃划船', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '哑铃', type: '拉', imageUrl: '', tags: ['拉力', '上肢'] },
  { id: 'tbar-row', name: 'T杠划船', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '杠铃', type: '拉' },
  { id: 'seated-row', name: '坐姿划船', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '绳索', type: '拉' },
  { id: 'one-arm-db-row', name: '单臂哑铃划船', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '哑铃', type: '拉' },
  { id: 'straight-arm-pulldown', name: '直臂下压', muscleGroup: '背', subMuscleGroup: '宽度', equipment: '绳索', type: '拉' },
  { id: 'hyperextension', name: '山羊挺身', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '徒手', type: '拉' },
  { id: 'hs-row', name: '悍马机划船', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '悍马机', type: '拉' },
  { id: 'machine-row', name: '器械划船', muscleGroup: '背', subMuscleGroup: '厚度', equipment: '固定器械', type: '拉' },
  // ==================== 肩部 (10) ====================
  { id: 'bb-ohp', name: '杠铃推举', muscleGroup: '肩', subMuscleGroup: '前束', equipment: '杠铃', type: '推', imageUrl: '', tags: ['推力', '上肢'] },
  { id: 'db-ohp', name: '哑铃推举', muscleGroup: '肩', subMuscleGroup: '前束', equipment: '哑铃', type: '推', imageUrl: '', tags: ['推力', '上肢'] },
  { id: 'arnold-press', name: '阿诺德推举', muscleGroup: '肩', subMuscleGroup: '前束', equipment: '哑铃', type: '推' },
  { id: 'smith-ohp', name: '史密斯推举', muscleGroup: '肩', subMuscleGroup: '前束', equipment: '固定器械', type: '推' },
  { id: 'lat-raise', name: '侧平举', muscleGroup: '肩', subMuscleGroup: '中束', equipment: '哑铃', type: '推', imageUrl: '', tags: ['推力', '上肢'] },
  { id: 'upright-row', name: '杠铃提拉', muscleGroup: '肩', subMuscleGroup: '中束', equipment: '杠铃', type: '推' },
  { id: 'cable-lat-raise', name: '绳索侧平举', muscleGroup: '肩', subMuscleGroup: '中束', equipment: '绳索', type: '推' },
  { id: 'face-pull', name: '面拉', muscleGroup: '肩', subMuscleGroup: '后束', equipment: '绳索', type: '拉', imageUrl: '', tags: ['拉力', '上肢'] },
  { id: 'reverse-fly', name: '反向飞鸟', muscleGroup: '肩', subMuscleGroup: '后束', equipment: '固定器械', type: '拉' },
  { id: 'pec-reverse-fly', name: '蝴蝶机反向飞鸟', muscleGroup: '肩', subMuscleGroup: '后束', equipment: '固定器械', type: '拉' },
  // ==================== 腿部 (12) ====================
  { id: 'bb-squat', name: '杠铃深蹲', muscleGroup: '腿', subMuscleGroup: '股四头', equipment: '杠铃', type: '腿', imageUrl: '', tags: ['腿部', '复合'] },
  { id: 'front-squat', name: '前蹲', muscleGroup: '腿', subMuscleGroup: '股四头', equipment: '杠铃', type: '腿' },
  { id: 'leg-press', name: '腿举', muscleGroup: '腿', subMuscleGroup: '股四头', equipment: '固定器械', type: '腿', imageUrl: '', tags: ['腿部', '推'] },
  { id: 'leg-extension', name: '腿屈伸', muscleGroup: '腿', subMuscleGroup: '股四头', equipment: '固定器械', type: '腿' },
  { id: 'bulgarian-split-squat', name: '保加利亚分腿蹲', muscleGroup: '腿', subMuscleGroup: '股四头', equipment: '哑铃', type: '腿' },
  { id: 'goblet-squat', name: '高脚杯深蹲', muscleGroup: '腿', subMuscleGroup: '股四头', equipment: '哑铃', type: '腿' },
  { id: 'rdl', name: '罗马尼亚硬拉', muscleGroup: '腿', subMuscleGroup: '股二头', equipment: '杠铃', type: '拉', imageUrl: '', tags: ['拉力', '下肢'] },
  { id: 'leg-curl', name: '腿弯举', muscleGroup: '腿', subMuscleGroup: '股二头', equipment: '固定器械', type: '腿' },
  { id: 'machine-leg-curl', name: '器械腿弯举', muscleGroup: '腿', subMuscleGroup: '股二头', equipment: '固定器械', type: '腿' },
  { id: 'hip-thrust', name: '臀推', muscleGroup: '腿', subMuscleGroup: '臀', equipment: '杠铃', type: '推' },
  { id: 'glute-bridge', name: '臀桥', muscleGroup: '腿', subMuscleGroup: '臀', equipment: '徒手', type: '推' },
  { id: 'single-glute-bridge', name: '单腿臀推', muscleGroup: '腿', subMuscleGroup: '臀', equipment: '哑铃', type: '推' },
  // ==================== 手臂 (10) ====================
  { id: 'bb-curl', name: '杠铃弯举', muscleGroup: '手臂', subMuscleGroup: '二头', equipment: '杠铃', type: '拉', imageUrl: '', tags: ['拉力', '手臂'] },
  { id: 'db-curl', name: '哑铃弯举', muscleGroup: '手臂', subMuscleGroup: '二头', equipment: '哑铃', type: '拉' },
  { id: 'preacher-curl', name: '牧师凳弯举', muscleGroup: '手臂', subMuscleGroup: '二头', equipment: '固定器械', type: '拉' },
  { id: 'hammer-curl', name: '锤式弯举', muscleGroup: '手臂', subMuscleGroup: '二头', equipment: '哑铃', type: '拉' },
  { id: 'cable-curl', name: '绳索弯举', muscleGroup: '手臂', subMuscleGroup: '二头', equipment: '绳索', type: '拉' },
  { id: 'tricep-pushdown', name: '三头下压', muscleGroup: '手臂', subMuscleGroup: '三头', equipment: '绳索', type: '推', imageUrl: '', tags: ['推力', '手臂'] },
  { id: 'close-grip-bench', name: '窄距卧推', muscleGroup: '手臂', subMuscleGroup: '三头', equipment: '杠铃', type: '推' },
  { id: 'french-press', name: '法式弯举', muscleGroup: '手臂', subMuscleGroup: '三头', equipment: '哑铃', type: '推' },
  { id: 'overhead-extension', name: '颈后臂屈伸', muscleGroup: '手臂', subMuscleGroup: '三头', equipment: '哑铃', type: '推' },
  { id: 'dip-tricep', name: '双杠臂屈伸（三头版）', muscleGroup: '手臂', subMuscleGroup: '三头', equipment: '徒手', type: '推' },
  // ==================== 核心 (6) ====================
  { id: 'crunch', name: '卷腹', muscleGroup: '腹', subMuscleGroup: '腹', equipment: '徒手', type: '核心' },
  { id: 'hanging-leg-raise', name: '悬垂举腿', muscleGroup: '腹', subMuscleGroup: '腹', equipment: '徒手', type: '核心' },
  { id: 'plank', name: '平板支撑', muscleGroup: '腹', subMuscleGroup: '腹', equipment: '徒手', type: '核心', imageUrl: '', tags: ['核心', '静态'] },
  { id: 'russian-twist', name: '俄罗斯转体', muscleGroup: '腹', subMuscleGroup: '腹', equipment: '徒手', type: '核心' },
  { id: 'cable-crunch', name: '绳索卷腹', muscleGroup: '腹', subMuscleGroup: '腹', equipment: '绳索', type: '核心' },
  { id: 'machine-crunch', name: '器械卷腹', muscleGroup: '腹', subMuscleGroup: '腹', equipment: '固定器械', type: '核心' },
  // ==================== 有氧 (6) ====================
  { id: 'incline-walk', name: '爬坡走', muscleGroup: '有氧', subMuscleGroup: '有氧', equipment: '有氧器械', type: '有氧' },
  { id: 'running', name: '跑步', muscleGroup: '有氧', subMuscleGroup: '有氧', equipment: '有氧器械', type: '有氧' },
  { id: 'cycling', name: '单车', muscleGroup: '有氧', subMuscleGroup: '有氧', equipment: '有氧器械', type: '有氧' },
  { id: 'rowing', name: '划船机', muscleGroup: '有氧', subMuscleGroup: '有氧', equipment: '有氧器械', type: '有氧' },
  { id: 'elliptical', name: '椭圆机', muscleGroup: '有氧', subMuscleGroup: '有氧', equipment: '有氧器械', type: '有氧' },
  { id: 'battle-rope', name: '战绳', muscleGroup: '有氧', subMuscleGroup: '有氧', equipment: '徒手', type: '有氧' },
];

export function getAllExercises(): ExerciseDef[] {
  // 后续会 merge 用户自定义动作
  return presetExercises;
}
