export type ToolDef = {
  id: string;
  name: string;
  desc: string;
  categoryId: CategoryId;
  /** 页面路径；占位工具统一指向 `/pages/stub/stub` */
  path: string;
  icon: string;
  tags: string[];
  requiredScopes?: string[];
};

export type CategoryId = 'social' | 'life' | 'efficiency' | 'creative' | 'games';

export const categories: {
  id: CategoryId;
  name: string;
  icon: string;
}[] = [
  { id: 'social', name: '社交协作', icon: '💬' },
  { id: 'life', name: '生活助手', icon: '☀️' },
  { id: 'efficiency', name: '效率工具', icon: '⚡' },
  { id: 'creative', name: '创意设计', icon: '🎨' },
  { id: 'games', name: '休闲', icon: '🎮' },
];

export const tools: ToolDef[] = [
  {
    id: 'decision-wheel',
    name: '决策转盘',
    desc: '写下选项，转盘帮你选',
    categoryId: 'social',
    path: '/package-tools/decision-wheel/index',
    icon: '🎡',
    tags: ['转盘', '随机', '决策'],
  },
  {
    id: 'scoreboard',
    name: '记分牌',
    desc: '游戏计分一目了然',
    categoryId: 'social',
    path: '/package-tools/scoreboard/index',
    icon: '🏆',
    tags: ['记分', '比赛'],
  },
  {
    id: 'truth-dare',
    name: '真心话大冒险',
    desc: '随机题目，聚会开场',
    categoryId: 'social',
    path: '/package-tools/truth-dare/index',
    icon: '🎲',
    tags: ['聚会', '随机'],
  },
  {
    id: 'danmaku',
    name: '手持弹幕',
    desc: '全屏大字，举着就用',
    categoryId: 'social',
    path: '/package-tools/danmaku/index',
    icon: '📱',
    tags: ['弹幕', '字幕'],
  },
  {
    id: 'relative-calc',
    name: '亲戚计算器',
    desc: '称呼换算',
    categoryId: 'social',
    path: '/package-tools/relative-calc/index',
    icon: '🧮',
    tags: ['亲戚', '称呼'],
  },
  {
    id: 'bill-split',
    name: '聚会分账',
    desc: '分摊结算，结果可复制',
    categoryId: 'social',
    path: '/package-tools/bill-split/index',
    icon: '🧾',
    tags: ['分账', '钱'],
    requiredScopes: ['clipboard'],
  },
  {
    id: 'coin',
    name: '掷硬币',
    desc: '正反面随机',
    categoryId: 'social',
    path: '/package-tools/coin/index',
    icon: '🪙',
    tags: ['硬币', '随机'],
  },
  {
    id: 'zen-clock',
    name: '禅意时钟',
    desc: '桌面翻页时钟',
    categoryId: 'life',
    path: '/package-tools/zen-clock/index',
    icon: '🕯️',
    tags: ['时钟', '翻页'],
  },
  {
    id: 'countdown',
    name: '倒数日',
    desc: '纪念日与倒计时',
    categoryId: 'life',
    path: '/package-tools/countdown/index',
    icon: '📅',
    tags: ['倒数', '纪念日'],
  },
  {
    id: 'beijing-trip',
    name: '北京向导',
    desc: '到京后地图+日程+核对，家人同行用',
    categoryId: 'life',
    path: '/package-beijing/index',
    icon: '🧭',
    tags: ['北京', '旅游', '故宫', '长城', '邯郸', '攻略', '向导', '家人'],
  },
  {
    id: 'cargo-quote',
    name: '装柜报价',
    desc: '集装箱单品试算、混装判定与报价摘要',
    categoryId: 'efficiency',
    path: '/package-tools/cargo-quote/index',
    icon: '📦',
    tags: ['装柜', '报价', '集装箱', '外贸', '体积'],
    requiredScopes: ['clipboard'],
  },
  {
    id: 'bmi',
    name: 'BMI计算器',
    desc: '身高体重算 BMI',
    categoryId: 'life',
    path: '/package-tools/bmi/index',
    icon: '⚖️',
    tags: ['bmi', '健康'],
  },
  {
    id: 'fill-light',
    name: '屏幕补光灯',
    desc: '可调亮度补光',
    categoryId: 'life',
    path: '/package-tools/fill-light/index',
    icon: '💡',
    tags: ['补光', '拍照'],
  },
  {
    id: 'ruler',
    name: '直尺',
    desc: '屏幕刻度测量',
    categoryId: 'life',
    path: '/package-tools/ruler/index',
    icon: '📏',
    tags: ['尺子', '测量'],
  },
  {
    id: 'discount',
    name: '折扣计算器',
    desc: '促销价快速计算',
    categoryId: 'life',
    path: '/package-tools/discount/index',
    icon: '💰',
    tags: ['折扣', '省钱'],
  },
  {
    id: 'body-fat',
    name: '体脂与代谢',
    desc: '基础代谢估算',
    categoryId: 'life',
    path: '/package-tools/body-fat/index',
    icon: '🔥',
    tags: ['代谢', '体脂'],
  },
  {
    id: 'pomodoro',
    name: '番茄钟',
    desc: '专注倒计时，到点轻提示',
    categoryId: 'efficiency',
    path: '/package-tools/pomodoro/index',
    icon: '🍅',
    tags: ['番茄', '计时', '专注'],
  },
  {
    id: 'qrcode',
    name: '二维码生成',
    desc: '生成二维码并保存',
    categoryId: 'efficiency',
    path: '/package-tools/qrcode/index',
    icon: '▦',
    tags: ['二维码', '扫码'],
    requiredScopes: ['album'],
  },
  {
    id: 'password',
    name: '密码生成器',
    desc: '按规则生成强密码',
    categoryId: 'efficiency',
    path: '/package-tools/password/index',
    icon: '🔑',
    tags: ['密码', 'pwd'],
    requiredScopes: ['clipboard'],
  },
  {
    id: 'unit-convert',
    name: '单位换算',
    desc: '常用单位互转',
    categoryId: 'efficiency',
    path: '/package-tools/unit-convert/index',
    icon: '🔄',
    tags: ['单位', '换算'],
  },
  {
    id: 'whiteboard',
    name: '白板',
    desc: '随手画，导出成图',
    categoryId: 'efficiency',
    path: '/package-canvas/whiteboard/index',
    icon: '✏️',
    tags: ['画板', '涂鸦'],
    requiredScopes: ['album'],
  },
  {
    id: 'palette',
    name: '调色板',
    desc: '配色方案与收藏',
    categoryId: 'creative',
    path: '/package-tools/palette/index',
    icon: '🎨',
    tags: ['配色', '颜色'],
    requiredScopes: ['clipboard'],
  },
  {
    id: 'grid-cut',
    name: '宫格切图',
    desc: '九宫格切图发朋友圈',
    categoryId: 'creative',
    path: '/package-canvas/grid-cut/index',
    icon: '🖼️',
    tags: ['切图', '九宫格'],
    requiredScopes: ['album', 'camera'],
  },
  {
    id: 'watermark',
    name: '图片水印',
    desc: '加水印，可调透明度',
    categoryId: 'creative',
    path: '/package-canvas/watermark/index',
    icon: '💧',
    tags: ['水印', '图片'],
    requiredScopes: ['album', 'camera'],
  },
  {
    id: 'text-to-image',
    name: '文字转图',
    desc: '长文排版成图分享',
    categoryId: 'creative',
    path: '/package-canvas/text-to-image/index',
    icon: '📝',
    tags: ['文字', '分享'],
    requiredScopes: ['album'],
  },
  {
    id: 'memo',
    name: '简易备忘录',
    desc: '临时记事，仅存本机',
    categoryId: 'efficiency',
    path: '/package-tools/memo/index',
    icon: '📋',
    tags: ['备忘', '笔记', '本地'],
  },
  {
    id: 'text-clean',
    name: '文本整理',
    desc: '去空白、字数行数统计',
    categoryId: 'efficiency',
    path: '/package-tools/text-clean/index',
    icon: '📄',
    tags: ['文本', '统计', 'trim'],
  },
  {
    id: 'wordbook',
    name: '单词本',
    desc: '日常与外贸词表，中英搜索与例句读音',
    categoryId: 'efficiency',
    path: '/package-learn/wordbook/index',
    icon: '📖',
    tags: ['英语', '单词', '外贸', '词表'],
  },
  {
    id: 'team-split',
    name: '随机分组',
    desc: '名单随机分队',
    categoryId: 'social',
    path: '/package-tools/team-split/index',
    icon: '👥',
    tags: ['分组', '聚会', '随机'],
  },
  {
    id: 'wooden-fish',
    name: '电子木鱼',
    desc: '敲击解压',
    categoryId: 'creative',
    path: '/package-tools/wooden-fish/index',
    icon: '🐟',
    tags: ['木鱼', '解压'],
  },
  {
    id: 'snake',
    name: '贪吃蛇',
    desc: '经典单机，触控转向',
    categoryId: 'games',
    path: '/package-game/snake/index',
    icon: '🐍',
    tags: ['贪吃蛇', '单机', '休闲'],
  },
];

export function findToolById(id: string): ToolDef | undefined {
  return tools.find((t) => t.id === id);
}

export function toolsByCategory(cid: CategoryId): ToolDef[] {
  return tools.filter((t) => t.categoryId === cid);
}
